name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python review.py

      - name: Post AI Review Comments
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comments = `${{ steps.ai_review.outputs.comments }}`;
            const repoFullName = process.env.GITHUB_REPOSITORY;
            const prNumber = process.env.GITHUB_PR_NUMBER;
            
            // Post the comment
            const [owner, repo] = repoFullName.split("/");
            github.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: comments
            });
